Int 3223 amzn normalization phase 1 delete product endpoint
patterninc/muffin_man pull request #52
Opened 2023-06-19 05:56 UTC by sanjjaymahalingam

Implementation of the deleteListingsItem SP API

Listings SP API (v2021-08-01)

DELETE /listings/2021-08-01/items/{sellerId}/{sku}
Clickup: https://app.clickup.com/t/2323726/INT-3223

2023-06-19 05:56 UTC, ssontakke commented
Task linked: [INT-3223 AMZN Normalization: Phase 1: Delete Product endpoint](https://app.clickup.com/t/2323726/INT-3223)

2023-06-19 06:11 UTC, ssontakke requested changes

2023-06-19 06:11 UTC, ssontakke commented on Gemfile
> +gem "mock_redis", ">=0.14"
I think these were dev dependencies in muffin_man.gemspec. Do we need to keep this as required dependencies?

2023-06-19 06:11 UTC, ssontakke commented on spec/muffin_man/listings_spec.rb
> +
Can we also add specs for case like - 
1. seller_id, sku combination not found
2. Cover - issue_locale parameter

2023-06-19 07:18 UTC, shubham-n-khanna approved these changes

2023-06-20 07:31 UTC, ssontakke approved these changes

2023-06-21 05:04 UTC, merged